name: Build connectors for BI tools

on:
  pull_request:
  push:
    paths:
      - 'bi-connectors/TableauConnector/**'
      - '.github/workflows/bi-connectors.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Pack Tableau JDBC connector
      id: pack-tableau-jdbc
      run: |
        zip -r opensearch_sql_jdbc.taco . -x *.taco
      working-directory: bi-connectors/TableauConnector/src
    - name: Upload Tableau JDBC connector
      if: steps.pack-tableau-jdbc.outcome == 'success'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: TableauConnectors
        path: bi-connectors/TableauConnector/src/opensearch_sql_jdbc.taco
