name: SQL JDBC Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17
          - 21
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    
    - name: Build with Gradle
      run: ./gradlew build test shadowJar
    
    - name: Create Artifact Path
      run: |
        mkdir -p sql-jdbc-builds
        cp ./build/libs/*.jar sql-jdbc-builds

    - name: Upload Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: sql-jdbc-java-${{ matrix.java }}
        path: sql-jdbc-builds
